services:
  app_proxy:
    environment:
      APP_HOST: pinano-podsync_server_1
      APP_PORT: 8145
    container_name: pinano-podsync_app_proxy_1
  server:
    image: tdeutsch/podsync:latest
    init: true
    volumes:
      - ${APP_DATA_DIR}/config/config.toml:/app/config.toml
      - ${UMBREL_ROOT}/home/Downloads/podsync:/app/data
    restart: on-failure
    stop_grace_period: 1m
    container_name: pinano-podsync_server_1