services:
  app_proxy:
    environment:
      APP_HOST: pinano-scrypted_server_1
      APP_PORT: 1080
    container_name: pinano-scrypted_app_proxy_1
  server:
    image: koussavery/scrypted:latest
    init: true
    volumes:
      - ${APP_DATA_DIR}/data:/server/volume
    restart: on-failure
    stop_grace_period: 1m
    container_name: pinano-scrypted_server_1
