services:
  app_proxy:
    environment:
      APP_HOST: pinano-dozzle_server_1
      APP_PORT: 8080
    container_name: pinano-dozzle_app_proxy_1
  server:
    image: amir20/dozzle:latest
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: on-failure
    stop_grace_period: 1m
    container_name: pinano-dozzle_server_1
