services:
  app_proxy:
    environment:
      APP_HOST: pinano-rtsp-simple-server_server_1
      APP_PORT: 8554
    container_name: pinano-rtsp-simple-server_app_proxy_1
  server:
    #image: kerberos/rtsp-simple-server:latest-rpi
    image: bluenviron/mediamtx:latest-rpi
    init: true
    #network_mode: host
    privileged: true
    tmpfs: /dev/shm:exec
    environment:
      MTX_PATHS_CAM_SOURCE: rpiCamera
    volumes:
      - ${APP_DATA_DIR}/mediamtx.yml:/mediamtx.yml
      - /run/udev:/run/udev:ro
    restart: on-failure
    stop_grace_period: 1m
    container_name: pinano-rtsp-simple-server_server_1